apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multik8s-site-tls
spec:
  secretName: multik8s-site-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - multik8s.site
    - www.multik8s.site
