name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "ticketing-448114"
          workload_identity_provider: "projects/980984347261/locations/global/workloadIdentityPools/github/providers/github-provider"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "microservice-cluster"
          location: "asia-south2-a"

      - name: "Deploy manifests"
        run: |
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod
