name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - run: cd client && docker build -t sayandafadar/client .

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push sayandafadar/client

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          service_account: "gh-deployer@ticketing-448114.iam.gserviceaccount.com"
          workload_identity_provider: "projects/980984347261/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "microservice-cluster"
          location: "asia-south2-a"

      - run: kubectl rollout restart deployment client-depl
