name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          service_account: "gh-deployer@ticketing-448114.iam.gserviceaccount.com"
          workload_identity_provider: "projects/980984347261/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "microservice-cluster"
          location: "asia-south2-a"

      - name: "Deploy manifests"
        run: |
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod
