name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t sayandafadar/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sayandafadar/tickets
      - uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/980984347261/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "gh-deployer@ticketing-448114.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ticketing-448114
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: microservice-cluster
          location: asia-south2-a
      - run: kubectl rollout restart deployment tickets-depl
